name: wedevs_dokan_wp_api
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  connectivity_plus: ^6.0.3
  fast_cached_network_image: ^1.2.9
  file_picker: ^8.0.3
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_riverpod: ^2.5.1
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  http: ^1.2.1
  image_cropper: ^5.0.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  isar: ^4.0.0-dev.14
  isar_flutter_libs: ^4.0.0-dev.14
  logger: ^2.3.0
  package_info_plus: ^8.0.0
  path: ^1.9.0
  path_provider: ^2.1.3

dev_dependencies:
  build_runner: ^2.4.10
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  ios: true
  android: true
  image_path: "assets/icons/app-icon-1024x1024.png"
  # command: dart run flutter_launcher_icons:main

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/icons/splash-icon-384x384.png"
  android: true
  ios: true
  # command: dart run flutter_native_splash:create

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/icons/
    - assets/images/
    - assets/json/
    - assets/svgs/
    - assets/types/
